### ISSUE TITLE
Example sketch DIYLESS gateway works, but this esphome gateway does not

### ISSUE THREAD

**Issue by remcodas** [Reproduktor/esphome-OpenthermGW#7]
I have run the example sketch from DIYLESS (master+slave shields stacked) from Ihor. Works fine. 
However, same hardware, same pins from this ESPhome gateway does not work. Boiler does not respond, only thermostat. 
Any idea? I have a Remeha Calenta and Isense thermostat.

**Comment by Reproduktor** [comment]
> Boiler does not respond, only thermostat.

Is that what you see in the logs - the request from Thermostat is incoming, but no reply from Boiler is coming back? Can you post the logs?

**Comment by Reproduktor** [comment]
By the way, master/slave configuration is referred to differently in my GW than Ihor refers to it in his sketch. Please check this out: https://github.com/Reproduktor/esphome-OpenthermGW/discussions/6

**Comment by Reproduktor** [comment]
Stale issue, closing, locking.
